### ISSUE TITLE
A question about the construction of Loss

### ISSUE THREAD

**Issue by ju1987yetchung** [limjoowon/maxwellnet#3]
![ques1](https://github.com/limjoowon/maxwellnet/assets/115963979/37d52d66-e1e1-474c-9f1e-67a57fa8734b)
hello,dear Author:
I have a question, I think this part that I pasted in the picture is the Loss of the Neural Network. the first two items are used to calculate x and z direction pml's loss. And the third and the forth items are used to simulate the function
![ques2](https://github.com/limjoowon/maxwellnet/assets/115963979/33d6fb79-5c98-43d8-b3b0-22a58a2f897e)
but could you tell me, why,in the source code, it is "+" used between these two items not "-", since we are finding the difference between these two items' value.
Thank You

**Comment by limjoowon** [comment]
Hi,

To get the equations implemented in the code, you need to expand the two curl operators and discard the derivatives to "y" as we assume that the sample is uniform along the y-axis. Then, we are left with two sets of equations: TE and TM modes, which are implemented in the code. Please note that TM mode is implemented in terms of electric fields rather than magnetic fields.
You can refer to the following figure, which explains this.

I hope this clarifies your question.

Thank you.

Best,

Joowon 

![te_tm](https://github.com/limjoowon/maxwellnet/assets/30259348/059d41b9-28c7-4572-870e-ce71fe55423e)
